apiVersion: v1
kind: Secret
metadata:
  name: jenkins-master-token
  namespace: jenkins
  annotations:
    kubernetes.io/service-account.name: jenkins-master
type: kubernetes.io/service-account-token
